### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by len0rd** [BYU-AUVSI/a6000_ros#1]
- [ ] For a couple of the top-level camera_connector functions, it would be nice to have more detailed failure returns. ROS could then pass that information back to the user. 
- [x] figure out wtf is happening to jpg metadata with opencv, if there's a way to publish it with the image, or if we need a separate metadata topic -> Focal Length is essential
- [ ] Subscribe to some type of metis topic to know when the plane is flying over the imaging search area to have it automatically start and stop camera capture
- [x] better cmake setup for whether or not you're using ros
- [ ] Get rid of custom ROS message. Since we're transporting the JPEG straight up, we should be able to look at EXIF data on the ground. This could remove 2 package dependencies: 1 on the custom ROS message(uav_msgs), and 1 on easyEXIF, both of which were kinda hacked into this driver so as to get it into a workable state. If this could run with just a sensor_msgs/CompressedImage msg that would be AWESOME. But there is also a possibility that ROS strips the EXIF somehow before sending, so double check that exif is available on a received CompressedImgWithMeta.image first

**Details**
On point 3: During the competition itself, we had someone ssh'ed into the plane who would turn the camera driver on/off whenever the plane started flying in the search path. This helps limit the number of images received with no targets, and thus helps reduce potential false positives identified by the autonomous imaging system. This also helps conserve bandwidth when the plane is flying long-distance waypoints. Note the imaging search path is fairly close to the flight line, which means network connection during imaging is pretty good.

**Comment by LauraYan** [comment]
Hi, is this head file #include <uav_msgs/CompressedImgWithMeta.h>  ROS hector_quadrotor package?

Sorry, I encountered one issue that this file( uav_msgs/CompressedImgWithMeta.h) can't be find out, and ROS version I am using is Melodic.

 Also,  did you use Kinetic version in this code?

Thank you for your replay in advance.

**Comment by len0rd** [comment]
Hi @LauraYan 

Per the readme, `uav_msgs/CompressedImgWithMeta` lives in the [BYU-AUVSI/uav_msgs](https://github.com/BYU-AUVSI/uav_msgs/tree/master/msg) repo. Adding that repo to your catkin_ws should resolve the include issue.

Also per the TODO in that section of the readme, I *think* we could move to using the standard ROS `CompressedImage.msg` type. All the information transported in `CompressedImgWithMeta` should be available in the JPEG EXIF data which could be decoded by a user as needed. Feel free to tackle that if your want to improve the repo :)

I think this was developed on Kinetic, but I believe Melodic would work with little to no changes. Havent touched ROS since Melodic so I cant speak to future versions.

Hopefully this helps! Been a while since I touched this code

**Comment by LauraYan** [comment]
😄Thank you so much to feed back me so swiftly. Thank you for your
information. I will research it.
I also reported a new issue.

Thank you again.
Happy holidays and new year.

Sincerely,

**Comment by LauraYan** [comment]
Thank you so much. I solved the problem as your guide.
Have a nice day

**Comment by LauraYan** [comment]
Hi len0rd,
 I feel the images captured by 6000 camera by your code have been save into files, so they are not in camera sd card, right?

I ran the a6000_ros_node, it worked
--------------------------------------- there are information I got---------------------------------------------
 rosrun a6000_ros a6000_ros_node
Startup Camera Connector
Startup Camera Connector
Detected 1 camera! Connecting to camera 1
PORT INFO::
	type: 4
	name: Universal Serial Bus
	path: usb:001,029

Camera info:
Manufacturer: Sony Corporation
Model: ILCE-6000
  Version: 3.0
  Serial Number: 00000000000000003282681006858933
Vendor Extension ID: 0x11 (1.0)
Vendor Extension Description: Sony PTP Extensions

Capture Formats: 
Display Formats: JPEG, Unknown(b301), ARW

Device Capabilities:
	File Download, No File Deletion, No File Upload
	No Image Capture, No Open Capture, Sony Capture

Connection Successful!
   camera getfile of capt0000.jpg
   camera getfile of capt0001.jpg
   camera getfile of capt0002.jpg
   camera getfile of capt0003.jpg
   camera getfile of capt0004.jpg
   camera getfile of capt0005.jpg
^C   camera getfile of capt0006.jpg
--------------------------------------------------informaiton End--------------------------------------------------

However, i can't find them on camera memory card, no find them in Linux by "find -name "*capt0*" in the root directory.
 I wonder how can I get these images. Thank you.

**Comment by len0rd** [comment]
Yep, thats an intentional feature of the code. Otherwise its possible it could fill the SD card and all subsequent captures would fail (if I'm remembering correctly). Once captured, the image is immediately downloaded into host memory then deleted off the sdcard. The a6000_ros_node publishes the images in a topic with the custom `CompressedImgWithMeta` type. Googling how to view ROS image topic data should help you solve how to view that topic.

In the driver code you can find places where `gp_camera_file_delete` is called which I believe is the call that deletes the file off the sdcard after it has been successfully downloaded onto the host machine. I'm guessing if you comment those out the file will remain on the sdcard

The camera connector class also has a [CameraConnector::writeImageToFile](https://github.com/BYU-AUVSI/a6000_ros/blob/master/src/camera_connector.cpp#L312) method which you could insert into the [GphotoCameraROS::run](https://github.com/BYU-AUVSI/a6000_ros/blob/master/src/ros/camera_ros.cpp#L59) loop to have every image saved on your host machine.

There's also a test application (in `src/test/main.cpp`) that you could modify. The test application does not use ROS at all. It simply connects to the camera, saves 10 photos onto the host machine, then exits

**Comment by LauraYan** [comment]
Yes, lenOrd,  I have to write a code similar to  CameraConnector::writeImageToFile()  or call glibphoto2 function  gp_file_save() to save images into disks.
Thank you for your reply.

**Comment by LauraYan** [comment]
Hey lenOrd,
 I  meet one more question, how can you compile this file with this type
"#include <uav_msgs/CompressedImgWithMeta.h> " in the /include/camera_node_ros.h file.
 I have to write it in"/home/myusername/catkin_ws/.../../../uav_msgs/CompressedImgWithMeta.h", 
it can compile without mistakes. Could you tell me where you put  uav_msgs project, so you can compile without absolute directory?
Thank you in advance.

**Comment by len0rd** [comment]
Hi @LauraYan 

Apologies for the late reply. Hopefully you figured this out already, but you should put the uav_msgs in your catkin_ws/src directory so it’s part of your catkin build.

Hopefully that works. As I’ve said in other comments it might be possible to remove that dependency entirely, especially if you don’t care about orientation data.
